---
name: Automated tests

on: pull_request

jobs:
  auto-formatting:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: 3.12.1
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install 'black[python2]==21.12b0'
          pip install click==8.0.2 # newer version is incompatible
      - name: Check formatting
        run: |
          black -t py27 --check web/
          black -t py27 --check web/**/*.py.example
  unit-tests-sqlite:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - uses: actions/checkout@v4
      - name: start SUT
        run: docker compose up --quiet-pull --detach --build
      - name: run django test
        run: docker compose run web './manage.py' test --failfast
  robot-tests:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - uses: actions/checkout@v4
      - name: start SUT
        run: docker compose up --quiet-pull --detach --build
      - name: Set up Python 3.12.1
        uses: actions/setup-python@v5
        with:
          python-version: 3.12.1
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install robotframework
          pip install robotframework-seleniumlibrary
      - name: wait SUT to start
        run: while ! curl -s -f 'http://localhost:3000/kipa' ; do sleep 2; docker ps; done
        shell: bash
      - name: run robot
        run: |
          robot \
          --outputdir ./test-report \
          --variable BROWSER:headlessfirefox \
          --variable KIPA_URL:'http://localhost:3000/kipa' \
          --exitonfailure \
          web/robot/perustoiminnot.robot
      - name: report
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: robot-test-report
          path: ./test-report
